services:
  - type: worker
    name: zapis-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_LINK
        sync: false
      - key: DB_PATH
        value: database.sqlite3
